"""Type definitions for the Autonomous Goal Engine.

Data model:
  Goal          — top-level persistent entity (stored in Redis HASH)
  TaskNode      — single executable step in the plan
  TaskGraph     — validated DAG of TaskNodes
  GoalState     — lifecycle state machine
  TaskStatus    — per-task execution status
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class GoalState(str, Enum):
    PLANNING = "planning"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    BLOCKED = "blocked"  # Blocked by policy or high-risk guard


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"  # Always requires confirmation regardless of autonomy mode


class AutonomyMode(str, Enum):
    """Controls how autonomously the Goal Engine executes tasks.

    ASSIST: Plan generated; no execution without manual approval per task.
    SEMI:   Auto-execute LOW and MEDIUM risk; confirm HIGH and CRITICAL.
    FULL:   Auto-execute LOW, MEDIUM, HIGH; confirm CRITICAL only.

    PolicyEngine always overrides autonomy mode — autonomy never bypasses policy.
    """
    ASSIST = "assist"
    SEMI = "semi"
    FULL = "full"


# ---------------------------------------------------------------------------
# TaskNode
# ---------------------------------------------------------------------------


class TaskNode(BaseModel):
    """A single executable step in a TaskGraph.

    Arguments are fully determined by the PlanGenerator so execution
    can proceed without a secondary LLM call.
    """

    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    description: str
    skill_name: str
    # Pre-determined arguments for the skill (generated by PlanGenerator)
    arguments: dict[str, str] = Field(default_factory=dict)
    required_capability: str = "controlled"
    risk_level: RiskLevel = RiskLevel.LOW
    dependencies: list[str] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    retries: int = 0
    max_retries: int = 2
    output_summary: str = ""
    error: str = ""
    started_at: str | None = None
    completed_at: str | None = None


# ---------------------------------------------------------------------------
# TaskGraph
# ---------------------------------------------------------------------------


class TaskGraph(BaseModel):
    """Directed Acyclic Graph of TaskNodes.

    Invariants enforced on construction:
    - All dependency IDs must reference valid node IDs
    - No cycles (Kahn's algorithm)
    """

    nodes: list[TaskNode] = Field(default_factory=list)

    @property
    def total_tasks(self) -> int:
        return len(self.nodes)

    def get_node(self, task_id: str) -> TaskNode | None:
        for node in self.nodes:
            if node.id == task_id:
                return node
        return None

    def validate_dag(self) -> tuple[bool, str]:
        """Validate DAG using topological sort (Kahn's algorithm).

        Returns (is_valid, error_message).
        """
        node_ids = {n.id for n in self.nodes}

        # Check all dependency references are valid
        for node in self.nodes:
            for dep_id in node.dependencies:
                if dep_id not in node_ids:
                    return (
                        False,
                        f"Task '{node.id}' references unknown dependency '{dep_id}'",
                    )

        # Kahn's algorithm: topological sort to detect cycles
        in_degree: dict[str, int] = {n.id: 0 for n in self.nodes}
        adj: dict[str, list[str]] = {n.id: [] for n in self.nodes}

        for node in self.nodes:
            for dep_id in node.dependencies:
                adj[dep_id].append(node.id)
                in_degree[node.id] += 1

        queue = [nid for nid, deg in in_degree.items() if deg == 0]
        visited = 0

        while queue:
            nid = queue.pop(0)
            visited += 1
            for child_id in adj[nid]:
                in_degree[child_id] -= 1
                if in_degree[child_id] == 0:
                    queue.append(child_id)

        if visited != len(self.nodes):
            return False, "Cycle detected in task dependency graph"

        return True, ""

    def get_executable_tasks(self) -> list[TaskNode]:
        """Return tasks ready to execute: status=PENDING, all deps DONE."""
        done_ids = {n.id for n in self.nodes if n.status == TaskStatus.DONE}
        return [
            n
            for n in self.nodes
            if n.status == TaskStatus.PENDING
            and all(dep_id in done_ids for dep_id in n.dependencies)
        ]

    def get_next_task(self) -> TaskNode | None:
        """Return the first executable task (depth-first ordering)."""
        executable = self.get_executable_tasks()
        return executable[0] if executable else None

    def compute_progress(self) -> float:
        """Progress 0–100 based on done tasks / total tasks."""
        if not self.nodes:
            return 0.0
        done = sum(1 for n in self.nodes if n.status == TaskStatus.DONE)
        return round((done / len(self.nodes)) * 100, 1)

    def is_complete(self) -> bool:
        return bool(self.nodes) and all(
            n.status == TaskStatus.DONE for n in self.nodes
        )

    def has_permanently_failed(self) -> bool:
        """True if any task failed and exhausted all retries."""
        return any(
            n.status == TaskStatus.FAILED and n.retries >= n.max_retries
            for n in self.nodes
        )

    def get_pending_tasks(self) -> list[TaskNode]:
        return [n for n in self.nodes if n.status == TaskStatus.PENDING]

    def get_failed_tasks(self) -> list[TaskNode]:
        return [
            n
            for n in self.nodes
            if n.status == TaskStatus.FAILED and n.retries >= n.max_retries
        ]


# ---------------------------------------------------------------------------
# Advanced Control Layer sub-models
# ---------------------------------------------------------------------------


class CognitiveBudget(BaseModel):
    """Per-goal spending limits and usage tracking.

    All limits are configurable at goal creation time with system-level
    defaults from config.  Once budget_exceeded is True the goal is
    paused automatically and requires manual resume.
    """

    # Hard limits (set at creation; configurable per goal)
    max_tokens_planning: int = 2000       # Total LLM tokens across all planning calls
    max_tokens_execution: int = 10000     # Reserved; currently tracked post-hoc
    max_replans: int = 5                  # Loosened from 3 — see stability.py rationale
    max_steps: int = 50                   # Mirrors goal.max_steps for budget tracking
    max_parallel_tasks: int = 1           # One task per tick (enforced by scheduler)
    max_memory_growth_bytes: int = 1_048_576  # 1 MB cumulative episodic writes
    max_runtime_seconds: int = 3600       # Mirrors goal.max_runtime_seconds

    # Tracked usage (updated by executor / orchestrator)
    tokens_used_planning: int = 0
    tokens_used_execution: int = 0
    replans_used: int = 0
    steps_executed: int = 0
    memory_growth: int = 0               # Cumulative bytes written to episodic memory

    # Violation state
    budget_exceeded: bool = False
    budget_exceeded_dimension: str = ""  # e.g. "tokens_planning", "replans", "steps"


class StabilityState(BaseModel):
    """Runtime stability tracking for intervention decisions.

    Enforces:
    - Exponential backoff on 3 consecutive task failures
    - Pause on 4 replans within 5 minutes (replan storm)
    - Lock on oscillating failure pattern
    - Block repeated policy violations on same capability
    """

    consecutive_failures: int = 0
    backoff_until: str | None = None          # ISO datetime; None = no backoff
    in_backoff: bool = False
    replan_timestamps: list[str] = Field(default_factory=list)  # ISO datetimes
    locked: bool = False                      # True if oscillation detected
    policy_block_counts: dict[str, int] = Field(default_factory=dict)
    last_intervention: str = ""               # ISO datetime of last intervention
    intervention_reason: str = ""


class GoalTelemetry(BaseModel):
    """Lightweight per-goal telemetry for observability.

    Tracks skill distribution, policy blocks, autonomy decisions, etc.
    Serialized as part of Goal in Redis HASH — intentionally compact.
    """

    skill_distribution: dict[str, int] = Field(default_factory=dict)
    policy_blocks: int = 0
    budget_exceeded_events: int = 0
    stability_interventions: int = 0
    autonomy_decisions: dict[str, int] = Field(default_factory=dict)  # "auto"/"blocked" → count
    template_id: str | None = None
    template_name: str = ""


# ---------------------------------------------------------------------------
# Goal
# ---------------------------------------------------------------------------


class Goal(BaseModel):
    """Persistent goal entity — stored as JSON in Redis HASH 'goals'."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    project_container_id: str = ""
    objective: str
    title: str = ""   # Short display title (auto-generated from objective)
    constraints: str = ""
    success_criteria: str = ""

    # Lifecycle
    state: GoalState = GoalState.PLANNING
    task_graph: TaskGraph = Field(default_factory=TaskGraph)
    progress: float = 0.0
    replan_count: int = 0
    step_count: int = 0
    # Plan lock: set True after first task success; prevents replanning on still-succeeding plans
    plan_locked: bool = False

    # Safety limits
    max_steps: int = 50
    max_runtime_seconds: int = 3600  # 1 hour

    # Timestamps
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    updated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    started_at: str | None = None
    completed_at: str | None = None

    # Origin
    chat_id: str = ""
    user_id: str = ""
    error: str = ""

    # Advanced Control Layer (Phase 17+)
    autonomy_mode: AutonomyMode = AutonomyMode.SEMI     # Default: confirm HIGH tasks
    budget: CognitiveBudget = Field(default_factory=CognitiveBudget)
    stability: StabilityState = Field(default_factory=StabilityState)
    telemetry: GoalTelemetry = Field(default_factory=GoalTelemetry)

    # Multi-Agent Orchestration Layer (Phase 18+)
    # allowed_capabilities: list of allowed capability levels for this goal.
    # Empty = unrestricted (inherits global CapabilityRegistry settings).
    # Set by AgentRuntime.create_goal() from agent.allowed_capabilities.
    allowed_capabilities: list[str] = Field(default_factory=list)
    # agent_id: owning agent (empty = standalone goal, not agent-managed)
    agent_id: str = ""

    # Priority Arbitration (1=lowest, 10=highest).
    # User-initiated goals default to 8; autonomous/agent goals default to 3.
    # tick() processes goals ordered highest-priority-first so user work is
    # never starved by background autonomous activity.
    priority: int = Field(default=5, ge=1, le=10)
    # Source: who initiated this goal ("user", "dashboard", "autonomous", "agent")
    source: str = "user"

    @field_validator("priority", mode="before")
    @classmethod
    def _clamp_priority(cls, v: int) -> int:
        return max(1, min(10, int(v)))

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def touch(self) -> None:
        """Update the updated_at timestamp."""
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def runtime_seconds(self) -> float:
        """Elapsed runtime since goal became ACTIVE."""
        if not self.started_at:
            return 0.0
        try:
            start = datetime.fromisoformat(self.started_at)
            now = datetime.now(timezone.utc)
            return (now - start).total_seconds()
        except Exception:
            return 0.0

    def is_runtime_exceeded(self) -> bool:
        return self.runtime_seconds() > self.max_runtime_seconds

    def is_steps_exceeded(self) -> bool:
        return self.step_count >= self.max_steps


# ---------------------------------------------------------------------------
# Observability event envelope
# ---------------------------------------------------------------------------


class GoalEvent:
    """Lightweight observability event — emitted at every state transition."""

    __slots__ = (
        "event_name",
        "goal_id",
        "task_id",
        "correlation_id",
        "project_container_id",
        "chat_id",
        "latency_ms",
        "model_used",
        "detail",
    )

    def __init__(
        self,
        event_name: str,
        goal_id: str,
        task_id: str = "",
        correlation_id: str | None = None,
        project_container_id: str = "",
        chat_id: str = "",
        latency_ms: int = 0,
        model_used: str = "",
        detail: str = "",
    ):
        self.event_name = event_name
        self.goal_id = goal_id
        self.task_id = task_id
        self.correlation_id = correlation_id or str(uuid4())
        self.project_container_id = project_container_id
        self.chat_id = chat_id
        self.latency_ms = latency_ms
        self.model_used = model_used
        self.detail = detail
